title: "Ismayil Rahimov"
description: "Personal portfolio of Ismayil Rahimov, a Computer Engineering student at ADA University."
url: "https://ismayil-7.github.io"  # Replace with your GitHub Pages URL
baseurl: ""
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap